name: backend-ci

on:
  pull_request:
    branches: [develop, main]
  workflow_dispatch:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13.1
      - name: Check out
        uses: actions/checkout@v2
      #- name: Cache
      #  uses: actions/cache@v2.1.0
      #  with:
      #    path: ~/go/pkg/mod
      #    key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #    restore-keys: |
      #      ${{ runner.os }}-go-

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Get dependencies
        run: go install ./...
      - name: Build
        run: go build ./...


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Test
        run:  go test ./... -v

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
