name: backend-ci

on:
  pull_request:
    branches: [develop, main]
  workflow_dispatch:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13.1
      - name: check out
        uses: actions/checkout@v2

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: go build ./backend/...
     #- name: get dependencies
     #run: go get -v -t -d ./...


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run:  go test ./backend/... -v

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
